version: '3.5'

services:
  postgres:
    container_name: caixadev-postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - "5432:5432"
    restart: "always"
